# Generated by Django 5.0.4 on 2024-10-02 19:09

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=chat.models.generate_random_chars, max_length=128, unique=True),
        ),
    ]
