# Generated by Django 5.0.4 on 2024-10-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_groupmessage_file_alter_groupmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
