# Generated by Django 5.0.4 on 2024-10-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='/default_avatar.png', null=True, upload_to='customers/'),
        ),
    ]
