# Generated by Django 5.0.4 on 2024-10-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
